name: Brainhack Project Form
description: This provides the backbone structure for your project description. Please fill out the form to submit your project!
title: "<My Project Name>"
labels: ["Hackathon Project"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        *We are very excited to meet you at the 2024 Pre-COSYNE Brainhack 🎉*
        *Please fill out this form to submit your project. You can find more information about the project submission process in [the guide](https://github.com/pre-cosyne-brainhack/hackathon2024/blob/main/.github/ISSUE_TEMPLATE/handbooks/projects.md).
        If at any time you need help or anything is unclear, please add a comment to alert the organizers.*
        Thank you!

  - type: input
    id: title
    attributes:
      label: Title
      description: Name of your awesome project. Please also update the title of the issue to be the title of your project.
    validations:
      required: true

  - type: textarea
    id: goals
    attributes:
      label: Short description and the goals for the 2024 Pre-COSYNE Brainhack
      description: Please provide a short description and goals for the hackathon, check [the guide](https://github.com/pre-cosyne-brainhack/hackathon2024/blob/main/.github/ISSUE_TEMPLATE/handbooks/projects.md#goals) for suggestions.
    validations:
      required: true

  - type: input
    id: link
    attributes:
      label: Link to the Project
      description: Please provide **one URL** for the project, e.g. a GitHub repository or issue ticket. See [the guide](https://github.com/pre-cosyne-brainhack/hackathon2024/blob/main/.github/ISSUE_TEMPLATE/handbooks/projects.md#link-to-project) for other suggestions.
    validations:
      required: true

  - type: input
    id: website-image
    attributes:
      label: Image for the Brainhack website and potential proceedings/report
      description: Please provide a link only (not required, but highly recommended).
    validations:
      required: false

  - type: textarea
    id: project-leads
    attributes:
      label: Project lead(s)
      description: Your name and GitHub login. You can add multiple leaders.
      placeholder: One per line, e.g., John Doe (@johndoe)
    validations:
      required: true

  - type: textarea
    id: skills
    attributes:
      label: Skills
      description: Please provide skills and skill levels that you expect contributors to have, so others can have better ideas if they can join. You can include non-technical skills, or simply write None. Check [the guide](https://github.com/pre-cosyne-brainhack/hackathon2024/blob/main/.github/ISSUE_TEMPLATE/handbooks/projects.md#onboarding-skills) for suggestions.
      placeholder: e.g., Python, data visualization, spike sorting, testing, translation, graphic design, etc.
    validations:
      required: true

  - type: textarea
    id: tutorials
    attributes:
      label: Recommended tutorials or documentation for new contributors
      description: Please provide links to information that might be helpful for new contributors.
    validations:
      required: false

  - type: textarea
    id: issues
    attributes:
      label: Good first issues
      description: If you welcome new contributors, please provide a list of good-first-issues (not required, but recommended), check [the guide](https://github.com/pre-cosyne-brainhack/hackathon2024/blob/main/.github/ISSUE_TEMPLATE/handbooks/projects.md#good-first-issues) for suggestions.
    validations:
      required: false

  - type: checkboxes
    id: coc
    attributes:
      label: "Please read and follow the Pre-COSYNE Brainhack Code of Conduct"
      description: Read here [the Pre-COSYNE Brainhack Code of Conduct](https://pre-cosyne-brainhack.github.io/hackathon2024/code-of-conduct/)
      options:
        - label: I agree to follow the Pre-COSYNE Brainhack Code of Conduct during the hackathon
          required: true
